# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672 # RabbitMQ default port
        - containerPort: 15672 # RabbitMQ management UI port (optional)

---
# RabbitMQ Service to expose RabbitMQ to producer and consumer
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  ports:
    - port: 5672
      targetPort: 5672
    - port: 15672 # Optional management UI
      targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP

---
# Producer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: artofghost/producer:latest
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service" # Service name for RabbitMQ
        imagePullPolicy: Always

---
# Consumer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: artofghost/consumer:latest
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service" # Service name for RabbitMQ
        imagePullPolicy: Always
