name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Producer Docker image
      run: |
        docker build -t artofghost/producer:latest -f Dockerfile.producer .
        docker tag artofghost/producer:latest artofghost/producer:latest

    - name: Build Consumer Docker image
      run: |
        docker build -t artofghost/consumer:latest -f Dockerfile.consumer .
        docker tag artofghost/consumer:latest artofghost/consumer:latest

    - name: Push Producer Docker image to DockerHub
      run: docker push artofghost/producer:latest

    - name: Push Consumer Docker image to DockerHub
      run: docker push artofghost/consumer:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Deploy to Kubernetes
      run: kubectl apply -f rabbitmq-deployment.yaml

